import {
  Arc,
  BouncingDots,
  CircularDots,
  Classic,
  Clock,
  Comet,
  Compass,
  Drive,
  Grid,
  LinearDots,
  Orbit,
  Pulse,
  Radar,
  Ring,
  Ripple,
  type SpinnerName,
  type SpinnerProps,
  Swirl,
} from "loading-dev";
import type { ComponentType } from "react";

export const SPINNER_COMPONENTS = {
  arc: Arc,
  "bouncing-dots": BouncingDots,
  "circular-dots": CircularDots,
  classic: Classic,
  clock: Clock,
  comet: Comet,
  compass: Compass,
  drive: Drive,
  grid: Grid,
  "linear-dots": LinearDots,
  orbit: Orbit,
  pulse: Pulse,
  radar: Radar,
  ring: Ring,
  ripple: Ripple,
  swirl: Swirl,
} satisfies Record<SpinnerName, ComponentType<SpinnerProps>>;
